### ISSUE TITLE
Create issues for Project Skeleton milestone

### ISSUE THREAD

**Issue by itspladd** [itspladd/react-3d-battleship#2]

**Comment by Bartek532** [comment]
Hi! Will this project be open source? I don't know Three.js, but I can help with React code (and probably with backend code) 😁

**Comment by itspladd** [comment]
Hi Bartek! For now, this is purely a personal project - I want to get some hands-on experience managing my own projects and milestones. But if that changes (or if I'm looking for contributors for other projects) I'll keep you in mind! : )

**Comment by Bartek532** [comment]
Ok, I recommend myself for the future 😁
